# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the deployment branch
  push:
    branches: ["deploy/gh-pages"]

  # Allows manual triggers
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          NEXT_PUBLIC_BASE_PATH: /md-next

      - name: Copy public assets
        run: |
          # Create md-next directory in out
          mkdir -p out/md-next
          
          # Copy all public assets to md-next directory
          cp -r public/* out/md-next/
          
          # Copy specific directories if they exist
          if [ -d "public/fonts" ]; then
            mkdir -p out/md-next/fonts
            cp -r public/fonts/* out/md-next/fonts/
          fi
          if [ -d "public/images" ]; then
            mkdir -p out/md-next/images
            cp -r public/images/* out/md-next/images/
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
